import fs from 'node:fs/promises';
import { Presentation, PresentationFile } from '../vendor-artifact-tool/dist/artifact_tool.mjs';

const OUT = 'D:/PlaceIntel/PlaceIntel_Review1.pptx';
const PREVIEW = 'D:/PlaceIntel/presentation_build/preview';
const W = 1280, H = 720;
const C = { navy:'#0B1F3A', blue:'#2563EB', purple:'#7C3AED', ink:'#10233F', muted:'#5B6B82', pale:'#F4F7FB', line:'#D8E1EE', white:'#FFFFFF', green:'#059669', amber:'#D97706' };

function addText(slide, text, x,y,w,h, size=18, color=C.ink, bold=false, align='left') {
  const s = slide.shapes.add({geometry:'textbox', position:{left:x,top:y,width:w,height:h}, fill:'none', line:{style:'solid',fill:'none',width:0}});
  s.text = text; s.text.style = {fontSize:size, color, bold, alignment:align, fontFamily:'Inter'}; return s;
}
function rect(slide,x,y,w,h,fill,line=C.line,r=12) { return slide.shapes.add({geometry:r?'roundRect':'rect',position:{left:x,top:y,width:w,height:h},fill,line:{style:'solid',fill:line,width:1},borderRadius:r?'rounded-xl':undefined}); }
function line(slide,x1,y1,x2,y2,color=C.line,width=2,arrow=false) { const left=Math.min(x1,x2), top=Math.min(y1,y2); return slide.shapes.add({geometry:'line',position:{left,top,width:Math.max(1,Math.abs(x2-x1)),height:Math.max(1,Math.abs(y2-y1))},fill:'none',line:{style:'solid',fill:color,width, endArrowType:arrow?'triangle':undefined}}); }
function title(slide,kicker,head,sub='') { addText(slide,kicker.toUpperCase(),72,36,1100,22,13,C.purple,true); addText(slide,head,72,64,1136,52,35,C.navy,true); if(sub) addText(slide,sub,72,120,1120,30,17,C.muted,false); line(slide,72,158,1208,158,C.line,1); }
function footer(slide,n,label='PLACEINTEL â€¢ REVIEW 1') { addText(slide,label,72,685,500,16,11,C.muted,true); addText(slide,String(n).padStart(2,'0'),1165,683,43,18,12,C.muted,true,'right'); }
function note(slide, text) { slide.speakerNotes.textFrame.setText(text+'\n\n[Sources]\nInternal project brief, architecture, timeline, and API contract in repository.'); }
function bulletList(slide, items, x,y,w, lineH=34, size=18, color=C.ink) { items.forEach((t,i)=>{ addText(slide,'â€¢',x,y+i*lineH,22,lineH,size,C.purple,true); addText(slide,t,x+26,y+i*lineH,w-26,lineH,size,color,false); }); }
function chip(slide, txt, x,y,w, fill=C.pale, color=C.blue) { rect(slide,x,y,w,28,fill,fill,14); addText(slide,txt,x,y+4,w,20,12,color,true,'center'); }

function addSlide(p, fn) { const s=p.slides.add(); s.background.fill=C.white; fn(s); return s; }

async function main(){
 const p=Presentation.create({slideSize:{width:W,height:H}});
 // 1
 addSlide(p,s=>{ s.background.fill=C.navy; addText(s,'PLACEINTEL',72,74,500,28,16,'#A7B8D4',true); addText(s,'AI-Powered Placement\nIntelligence Platform',72,150,720,150,52,C.white,true); addText(s,'Review 1 â€¢ Software Engineering Project',76,322,650,32,22,'#D8E1EE'); addText(s,'CHARUSAT University\nDepartment of Computer Engineering',76,406,430,60,18,'#B7C7DE'); rect(s,835,108,290,290,'#142F56','#2A4D7C',145); addText(s,'PI',871,177,218,100,78,C.white,true,'center'); addText(s,'Transforming placement information\ninto placement intelligence.',850,430,260,58,17,'#D8E1EE',false,'center'); addText(s,'Team members â€¢ Guide name â€¢ Academic Year',76,620,600,24,14,'#A7B8D4'); note(s,'Open with the operational problem and the platform thesis.'); });
 // 2
 addSlide(p,s=>{ title(s,'01 â€¢ Context','Placement information is fragmented at the moment students need it most','The current process creates search cost, missed updates, and avoidable manual work.'); const cards=[['EMAIL','Announcements'],['GROUPS','WhatsApp / Google Groups'],['NOTICES','PDFs & circulars'],['SPREADSHEETS','Manual tracking']]; cards.forEach((c,i)=>{const x=72+(i%2)*290,y=220+Math.floor(i/2)*128; rect(s,x,y,250,96,C.pale,C.line,16); addText(s,c[0],x+18,y+17,210,18,12,C.purple,true); addText(s,c[1],x+18,y+43,210,24,19,C.navy,true);}); rect(s,700,216,470,246,'#EEF2FF','#C7D2FE',22); addText(s,'THE CONSEQUENCE',730,244,330,20,13,C.purple,true); addText(s,'Students miss deadlines.\nThe T&P Cell cannot see the full picture.',730,284,400,76,28,C.navy,true); addText(s,'No shared source of truth â†’ no reliable intelligence.',730,392,370,28,17,C.muted); footer(s,2); note(s,'Use the left side to make the fragmentation tangible; land on the â€œsource of truthâ€ gap.'); });
 // 3
 addSlide(p,s=>{ title(s,'02 â€¢ Existing System','The manual workflow breaks at retrieval, consistency, and reporting','A centralized platform is necessary because todayâ€™s process is not designed for scale.'); addText(s,'TODAY',90,198,420,28,16,C.muted,true); addText(s,'WITH PLACEINTEL',710,198,420,28,16,C.purple,true); const rows=[['Announcements','Email + groups','Central feed'],['Records','Manual sheets','Structured repository'],['Discovery','Ask around / search files','Search + filters'],['Insights','Ad hoc reporting','Analytics dashboard'],['Data quality','Duplicates / drift','Validation + ownership']]; rows.forEach((r,i)=>{const y=244+i*70; line(s,72,y-14,1208,y-14,C.line,1); addText(s,r[0],90,y,220,24,17,C.ink,true); addText(s,r[1],360,y,280,24,17,C.muted); addText(s,'â†’',628,y,44,24,22,C.purple,true,'center'); addText(s,r[2],710,y,380,24,17,C.navy,true);}); footer(s,3); note(s,'Frame this as a system analysis, not criticism of peopleâ€”the process is the constraint.'); });
 // 4
 addSlide(p,s=>{ title(s,'03 â€¢ Proposed Solution','PlaceIntel turns scattered notices into a searchable placement system','A modular platform for students and the Training & Placement Cell, with AI as an extensible layer.'); const steps=[['1','COLLECT','Notices, companies, drives'],['2','STRUCTURE','Eligibility, skills, deadlines'],['3','DISCOVER','Search, filters, dashboards'],['4','INTELLIGENCE','Grounded natural-language queries']]; steps.forEach((st,i)=>{const x=78+i*285; rect(s,x,248,240,156,i===3?'#F3E8FF':C.pale,i===3?'#DDD6FE':C.line,18); rect(s,x+18,270,44,44,i===3?C.purple:C.blue,i===3?C.purple:C.blue,22); addText(s,st[0],x+18,281,44,20,18,C.white,true,'center'); addText(s,st[1],x+78,270,140,18,12,C.purple,true); addText(s,st[2],x+78,302,140,48,17,C.navy,true); if(i<3) line(s,x+240,326,x+280,326,C.blue,3,true);}); addText(s,'Modular monolith today â†’ AI-ready platform tomorrow',280,500,720,34,24,C.navy,true,'center'); footer(s,4); note(s,'The platform is useful on day one without waiting for the chatbot; the AI layer compounds value later.'); });
 // 5
 addSlide(p,s=>{ title(s,'04 â€¢ Objectives','Build a reliable placement operating system for CHARUSAT','The first release prioritizes a strong information foundation, then adds intelligence.'); const objs=['Centralized placement repository','Company & drive management','Student-friendly search & filters','Eligibility and Fit Score explanation','Analytics for placement decisions','AI-assisted information retrieval','Cloud-ready, modular architecture']; objs.forEach((t,i)=>{const col=i<4?0:1; const row=col?i-4:i; const x=90+col*540,y=214+row*80; addText(s,String(i+1).padStart(2,'0'),x,y,40,28,18,C.purple,true); addText(s,t,x+58,y,400,28,20,C.navy,true); line(s,x+58,y+43,x+470,y+43,C.line,1);}); footer(s,5); note(s,'Read these as design objectives that guide scope and trade-offs.'); });
 // 6
 addSlide(p,s=>{ title(s,'05 â€¢ Functional Requirements','Seven capabilities define the first usable product','Each capability maps directly to a student or admin workflow.'); const fs=[['01','AUTH','Secure login & roles'],['02','COMPANIES','Company catalogue'],['03','DRIVES','Placement lifecycle'],['04','ELIGIBILITY','Rules + fit signal'],['05','SEARCH','Filters & discovery'],['06','ANALYTICS','Counts & trends'],['07','ADMIN','Governance & uploads']]; fs.forEach((f,i)=>{const x=72+(i%4)*286,y=214+Math.floor(i/4)*160; rect(s,x,y,250,122,C.pale,C.line,18); addText(s,f[0],x+18,y+16,38,18,12,C.purple,true); addText(s,f[1],x+18,y+44,208,22,19,C.navy,true); addText(s,f[2],x+18,y+78,210,24,15,C.muted);}); footer(s,6); note(s,'Point out that these are end-to-end product capabilities, not isolated screens.'); });
 // 7
 addSlide(p,s=>{ title(s,'06 â€¢ Quality Attributes','Trust is a feature: the platform must be fast, secure, and maintainable','Non-functional requirements protect the experience as usage and scope grow.'); const q=[['SCALABILITY','Grow from one batch to many cohorts'],['SECURITY','JWT, hashing, validation, RBAC'],['PERFORMANCE','Fast search and predictable APIs'],['RELIABILITY','Backups, logging, recoverable failures'],['MAINTAINABILITY','Layered modules, shared contracts'],['EXTENSIBILITY','AI, notifications, mobile later'],['AVAILABILITY','Dockerized, cloud-ready deployment']]; q.forEach((it,i)=>{const y=204+i*57; addText(s,it[0],92,y,180,22,14,C.purple,true); addText(s,it[1],300,y,690,22,18,C.navy,true); line(s,92,y+34,1130,y+34,C.line,1);}); footer(s,7); note(s,'Emphasize that architecture choices are justified by these quality attributes.'); });
 // 8
 addSlide(p,s=>{ title(s,'07 â€¢ Technology Stack','A pragmatic stack keeps the core simple and the future open','Selected technologies match the teamâ€™s need for speed, structure, and AI extensibility.'); const cols=[['WEB','React + TypeScript','Component reuse, typed UI'],['API','Node.js + Express','Fast REST iteration'],['DATA','PostgreSQL + Prisma','Integrity, migrations, safe access'],['OPS','Docker + GitHub','Reproducible environments'],['FUTURE','AWS + pgvector + FastAPI','Cloud scale + RAG service']]; cols.forEach((c,i)=>{const x=72+i*226; rect(s,x,230,198,220,i===4?'#F3E8FF':C.pale,i===4?'#DDD6FE':C.line,18); addText(s,c[0],x+18,250,160,18,12,C.purple,true); addText(s,c[1],x+18,292,160,60,21,C.navy,true); addText(s,c[2],x+18,372,160,46,15,C.muted);}); footer(s,8); note(s,'Technology choices are intentionally boring where reliability matters and extensible where AI will evolve.'); });
 // 9
 addSlide(p,s=>{ title(s,'08 â€¢ Architecture','A modular monolith gives the team clean boundaries without premature complexity','Independent layers can evolve into services later without rewriting the product.'); const nodes=[['React Frontend',72,224,280,70,C.blue],['Express REST API',72,344,280,70,C.purple],['Prisma ORM',72,464,280,70,C.navy],['PostgreSQL',72,584,280,70,C.green]]; nodes.forEach(n=>{rect(s,n[1],n[2],n[3],n[4],n[5],n[5],16); addText(s,n[0],n[1],n[2]+23,n[3],24,20,C.white,true,'center');}); for(let i=0;i<3;i++) line(s,212,294+i*120,212,340+i*120,C.line,3,true); rect(s,500,262,310,120,'#F3E8FF','#DDD6FE',18); addText(s,'FUTURE EXTENSIONS',524,284,260,18,13,C.purple,true); addText(s,'Email Collector â€¢ AI Service\npgvector â€¢ AWS Cloud',524,316,260,48,18,C.navy,true); line(s,352,379,500,322,C.purple,2,true); addText(s,'Monorepo boundary: shared contracts + independent delivery',500,470,560,30,19,C.muted,true); footer(s,9); note(s,'Explain the architecture as a deliberate modular monolith, with AI isolated behind a service boundary.'); });
 // 10
 addSlide(p,s=>{ title(s,'09 â€¢ Data Model','The relational model makes placement intelligence explainable','Core entities preserve integrity today and provide clean retrieval units for AI tomorrow.'); const ents=[['STUDENT',100,252,220,70,C.blue],['COMPANY',500,210,220,70,C.purple],['PLACEMENT',500,352,220,70,C.navy],['SKILL',900,252,220,70,C.green],['PLACEMENT\nSKILL',900,420,220,70,C.amber]]; ents.forEach(e=>{rect(s,e[1],e[2],e[3],e[4],e[5],e[5],16); addText(s,e[0],e[1],e[2]+20,e[3],30,18,C.white,true,'center');}); line(s,320,287,500,245,C.line,2,true); line(s,320,287,500,387,C.line,2,true); line(s,720,245,900,287,C.line,2,true); line(s,720,387,900,455,C.line,2,true); line(s,1010,322,1010,420,C.line,2,true); addText(s,'Relational integrity â€¢ auditability â€¢ future vector compatibility',240,570,800,30,22,C.navy,true,'center'); footer(s,10); note(s,'Keep the ERD intentionally simplified for review 1; the point is the relationship design, not every attribute.'); });
 // 11
 addSlide(p,s=>{ title(s,'10 â€¢ API Design','Stable API contracts let frontend and backend teams move in parallel','REST resources, JSON responses, and versioning keep integration predictable.'); rect(s,72,218,520,340,C.navy,C.navy,18); addText(s,'/api/v1',102,248,450,28,22,'#A7B8D4',true); const apis=['GET    /companies','POST   /companies','GET    /placements','POST   /placements','PUT    /placements/:id','DELETE /placements/:id','GET    /analytics']; apis.forEach((a,i)=>addText(s,a,102,298+i*34,420,24,18,C.white,false)); rect(s,670,218,500,340,C.pale,C.line,18); addText(s,'CONTRACT PRINCIPLES',704,248,410,20,13,C.purple,true); bulletList(s,['Resource-based URLs','JWT authorization','Standard status codes','Zod validation','Predictable JSON responses'],704,296,400,42,18); footer(s,11); note(s,'Use this slide to show how the team avoids integration surprises before implementation begins.'); });
 // 12
 addSlide(p,s=>{ title(s,'11 â€¢ Development Workflow','Dependencies first; parallel delivery second','The workflow front-loads shared decisions, then unlocks independent workstreams.'); const steps=[['01','Requirements'],['02','Architecture'],['03','Database'],['04','API'],['05','Parallel build'],['06','Integration'],['07','Testing'],['08','Deployment'],['09','AI layer']]; steps.forEach((st,i)=>{const x=72+i*124; const y=i===4?260:320; rect(s,x,y,106,74,i===4?'#F3E8FF':C.pale,i===4?'#DDD6FE':C.line,16); addText(s,st[0],x+12,y+13,82,16,12,C.purple,true); addText(s,st[1],x+12,y+35,82,30,15,C.navy,true); if(i<8) line(s,x+106,y+37,x+122,(i+1===4?260:320)+37,C.blue,2,true);}); addText(s,'Parallel tracks after API contract',512,214,360,24,18,C.purple,true,'center'); addText(s,'Frontend  â€¢  Backend  â€¢  DevOps  â€¢  AI preparation',400,500,520,26,21,C.navy,true,'center'); footer(s,12); note(s,'The API contract is the handoff point that enables parallel development.'); });
 // 13
 addSlide(p,s=>{ title(s,'12 â€¢ Team Responsibilities','Clear ownership keeps architecture, delivery, and AI work connected','Responsibilities are separated by specialty, with shared integration checkpoints.'); const cols=[['MEMBER 1','Architecture & Data','Software architecture\nDatabase design\nDevOps & cloud deployment',C.blue],['MEMBER 2','Product Delivery','Backend development\nFrontend development\nREST API implementation',C.purple],['MEMBER 3','AI & Intelligence','Data processing\nNLP preparation\nRAG pipeline',C.green]]; cols.forEach((c,i)=>{const x=90+i*370; rect(s,x,230,300,250,C.pale,C.line,18); rect(s,x,230,300,56,c[3],c[3],18); addText(s,c[0],x+18,248,264,20,13,C.white,true); addText(s,c[1],x+22,316,256,30,24,C.navy,true); addText(s,c[2],x+22,370,256,80,18,C.muted);}); addText(s,'Shared checkpoint: integration, testing, and review evidence',310,560,660,28,20,C.navy,true,'center'); footer(s,13); note(s,'Position ownership as a delivery advantage, not silos.'); });
 // 14
 addSlide(p,s=>{ title(s,'13 â€¢ Timeline','A 15-week roadmap converts the architecture into evidence','Milestones sequence the foundation, product build, intelligence, and hardening.'); const weeks=['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15']; weeks.forEach((w,i)=>{addText(s,w,300+i*52,192,24,18,12,C.muted,true,'center'); line(s,300+i*52,216,300+i*52,602,C.line,1);}); const tasks=[['Requirements',1,2,C.blue],['Architecture',2,2,C.purple],['Database',3,2,C.navy],['UI + API',5,4,C.blue],['Integration',9,2,C.purple],['Analytics + automation',11,2,C.green],['Cloud deployment',13,1,C.amber],['AI integration + testing',14,2,C.navy]]; tasks.forEach((t,i)=>{const y=240+i*43; addText(s,t[0],82,y,200,22,16,C.navy,true); rect(s,300+(t[1]-1)*52,y, t[2]*52-8,24,t[3],t[3],12);}); footer(s,14); note(s,'The roadmap is a dependency-based plan; dates are a planning baseline, not a promise of finished AI capabilities.'); });
 // 15
 addSlide(p,s=>{ title(s,'14 â€¢ Future Scope','The core platform creates a runway for intelligence','Future enhancements become safer once the data model, permissions, and APIs are stable.'); const roadmap=[['NOW','Structured placement data'],['NEXT','Email collection + notifications'],['THEN','RAG chatbot + semantic search'],['LATER','Mobile app + multi-university']]; roadmap.forEach((r,i)=>{const x=90+i*290; rect(s,x,260,240,150,i===2?'#F3E8FF':C.pale,i===2?'#DDD6FE':C.line,20); addText(s,r[0],x+20,284,200,20,13,C.purple,true); addText(s,r[1],x+20,322,200,50,21,C.navy,true); if(i<3) line(s,x+240,335,x+280,335,C.purple,3,true);}); addText(s,'AI is a force multiplier for trusted dataâ€”not a substitute for it.',220,520,840,32,24,C.navy,true,'center'); footer(s,15); note(s,'Close the future-scope story with sequencing: foundation first, intelligence second.'); });
 // 16
 addSlide(p,s=>{ title(s,'15 â€¢ Expected Outcomes','Review 1 establishes the foundation for a production-ready build','The next review can focus on implementation evidence because the design decisions are now explicit.'); const outs=[['01','ONE SOURCE OF TRUTH'],['02','FASTER DISCOVERY'],['03','EXPLAINABLE INSIGHTS'],['04','SCALABLE FOUNDATION']]; outs.forEach((o,i)=>{const x=90+(i%2)*540,y=230+Math.floor(i/2)*145; rect(s,x,y,470,106,C.pale,C.line,18); addText(s,o[0],x+24,y+24,44,22,18,C.purple,true); addText(s,o[1],x+90,y+24,340,24,20,C.navy,true); addText(s,['Centralized repository','Search, filters, and eligibility','Analytics + Fit Score + grounded AI','Modular, secure, cloud-ready'][i],x+90,y+58,340,24,16,C.muted);}); footer(s,16); note(s,'These are expected outcomes at the system level; do not present them as measured results yet.'); });
 // 17
 addSlide(p,s=>{ s.background.fill=C.navy; addText(s,'REVIEW 1 COMPLETE',72,78,500,24,14,'#A7B8D4',true); addText(s,'The foundation is ready\nfor implementation.',72,160,700,130,52,C.white,true); addText(s,'Problem analyzed â€¢ Requirements identified â€¢ Architecture finalized\nDatabase + API designs prepared â€¢ Roadmap and ownership defined',76,340,760,54,19,'#D8E1EE'); rect(s,890,155,220,220,'#142F56','#2A4D7C',110); addText(s,'PI',930,218,140,70,58,C.white,true,'center'); addText(s,'Thank you',72,585,400,40,27,'#D8E1EE',true); addText(s,'Transforming placement information into placement intelligence.',72,635,700,24,16,'#A7B8D4'); note(s,'End with the Review 1 handoff: the team has reduced ambiguity and is ready to build.'); });
 await fs.mkdir(PREVIEW,{recursive:true});
 for (const [i,s] of p.slides.items.entries()) { const b=await p.export({slide:s,format:'png',scale:1}); await fs.writeFile(`${PREVIEW}/slide-${String(i+1).padStart(2,'0')}.png`,new Uint8Array(await b.arrayBuffer())); }
 const montage=await p.export({format:'webp',montage:true,scale:1}); await fs.writeFile(`${PREVIEW}/montage.webp`,new Uint8Array(await montage.arrayBuffer()));
 const pptx=await PresentationFile.exportPptx(p); await pptx.save(OUT); console.log(OUT);
}
main().catch(e=>{console.error(e);process.exit(1)});

